[[language]]
name="c"
indent={tab-width=4, unit = "    "}

[[language]]
name="cpp"
indent={tab-width=4, unit = "    "}

[[language]]
name = "python"
scope = "source.python"
language-servers = ["pyright"]
indent={tab-width=4, unit = "    "}

[[language]]
name = "java"
scope = "java"
language-servers = ["jdtls"]
indent={tab-width=4, unit = "    "}
