theme = "onedark_transparent"
[keys.insert]
f = {d = "normal_mode"}

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
center = ["file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
